---
- name: create www directory
  file:
    path: '{{ www_dir }}'
    state: directory
    owner: '{{ installation_os_user }}'

- name: install simplehttp service
  template:
    src: 'simplehttp.service'
    dest: '/etc/systemd/system/'

- name: Make sure simplehttp is started and enabled to start on boot
  systemd:
    name: 'simplehttp'
    state: 'started'
    enabled: 'yes'

- name: Copy files to serve
  copy:
    src: "{{ item }}"
    dest: '{{ www_dir }}'
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"
    mode: 0600
  with_items: '{{ www_files}}'
